supergraph:
  # The socket address and port to listen on
  # Required for Heroku
  listen: "0.0.0.0:${env.PORT}"
cors:
  origins:
    - http://localhost:3000 # Allows any locally-running client to run against your Router
    - https://studio.apollographql.com # Allows Apollo Studio to still run queries against your Router
headers:
  all:
    request:
      - propagate:
          named: "Authorization"
subscription:
  enabled: true
  mode:
    passthrough:
      all: # The router uses these subscription settings UNLESS overridden per-subgraph
        path: /graphql # The absolute URL path to use for subgraph subscription endpoints (Default: /ws)
        protocol: graphql_ws # The WebSocket-based subprotocol to use for subscription communication (Default: graphql_ws)
        heartbeat_interval: 10s # Optional and 'disable' by default, also supports 'enable' (set 5s interval) and custom values for intervals, e.g. '100ms', '10s', '1m'.
